Report 50°C on virtual TMC heater channel for any driver being active
Duet3D/RepRapFirmware pull request #180
Opened 2018-06-18 11:45 UTC by wilriker

This one closes https://forum.duet3d.com/topic/5536/status-based-fan-mode - if I did not miss anything where else it would be required to check for an non-disabled driver. ;-)

2018-06-19 11:18 UTC, wilriker commented
I have amended this commit as I forgot to add the `const` modifier to the new method that checks if any driver is currently active/idle.

2018-08-07 16:09 UTC, dc42 requested changes
I cannot accept this PR as it stands because it doesn't distinguish between drivers that are on the Duet, drivers that are on a DueX2 or DueX5, and external drivers. Each virtual heater channel should show 50C only when _relevant_ drivers are active.

2018-08-07 16:14 UTC, wilriker commented
I will fix that in Thursday. Thanks for spotting.

2018-08-09 09:30 UTC, wilriker commented
While adjusting this I found something strange. There are up to 10 drivers when using Duet+DueX5. But there is `constexpr size_t DRIVES = 9;` in `Configuration.h` and this limits it to only 9 drivers max. Why is that? How is the last driver on DueX5 used at all?

Everything I found related to drivers has only a length of 9.

2018-08-09 11:07 UTC, wilriker commented
Fixed. This will now check a maximum of 5 drivers per board. This means it will never check drivers 10 and 11.

2019-01-04 11:12 UTC, dc42 commented
Thanks for the reminder. Why did you choose 50C? The complication I can see is that if you have a fan set to run thermostatically on both CPU temperature and driver temperature, you can only choose one temperature for both. So the value we choose to report for drivers that are active matters.

2019-01-11 12:32 UTC, wilriker commented
I thought about the temperature a little and I think 35C or 40C would probably be a better temperature in regards to thermostatically controlled fans that also monitor CPU. 35C might be a bit over-cautious but I think 40C would be good.

What do you think?

2019-02-01 14:39 UTC, wilriker commented
I have updated this PR to the latest commit on `dev` branch since there were some incompatible changes. I also hid the method checking for active drivers behind 
```c
#if HAS_SMART_DRIVERS
...
#endif
```
and let it only check up until `MaxSmartDrivers` instead of MaxTotalDrivers. This can be easily changed back in case this method needs to be used somehow on Duet 0.6/0.85.

Also I lowered the returned temperature to 40°C.

2026-07-08 10:23 UTC, closed without merging